/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedForYouRouteImport } from './routes/_authenticated/for-you'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedUpcomingRouteImport } from './routes/_authenticated/upcoming'
import { Route as AuthenticatedExhibitionExhibitionIdRouteImport } from './routes/_authenticated/exhibition.$exhibitionId'
import { Route as AuthenticatedReservationReservationIdRouteImport } from './routes/_authenticated/reservation.$reservationId'
import { Route as AuthenticatedExhibitionExhibitionIdBookRouteImport } from './routes/_authenticated/exhibition.$exhibitionId.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedForYouRoute = AuthenticatedForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpcomingRoute = AuthenticatedUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExhibitionExhibitionIdRoute =
  AuthenticatedExhibitionExhibitionIdRouteImport.update({
    id: '/exhibition/$exhibitionId',
    path: '/exhibition/$exhibitionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservationReservationIdRoute =
  AuthenticatedReservationReservationIdRouteImport.update({
    id: '/reservation/$reservationId',
    path: '/reservation/$reservationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExhibitionExhibitionIdBookRoute =
  AuthenticatedExhibitionExhibitionIdBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedExhibitionExhibitionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/for-you': typeof AuthenticatedForYouRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/upcoming': typeof AuthenticatedUpcomingRoute
  '/exhibition/$exhibitionId': typeof AuthenticatedExhibitionExhibitionIdRouteWithChildren
  '/reservation/$reservationId': typeof AuthenticatedReservationReservationIdRoute
  '/exhibition/$exhibitionId/book': typeof AuthenticatedExhibitionExhibitionIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/for-you': typeof AuthenticatedForYouRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/upcoming': typeof AuthenticatedUpcomingRoute
  '/exhibition/$exhibitionId': typeof AuthenticatedExhibitionExhibitionIdRouteWithChildren
  '/reservation/$reservationId': typeof AuthenticatedReservationReservationIdRoute
  '/exhibition/$exhibitionId/book': typeof AuthenticatedExhibitionExhibitionIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/for-you': typeof AuthenticatedForYouRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/upcoming': typeof AuthenticatedUpcomingRoute
  '/_authenticated/exhibition/$exhibitionId': typeof AuthenticatedExhibitionExhibitionIdRouteWithChildren
  '/_authenticated/reservation/$reservationId': typeof AuthenticatedReservationReservationIdRoute
  '/_authenticated/exhibition/$exhibitionId/book': typeof AuthenticatedExhibitionExhibitionIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/for-you'
    | '/profile'
    | '/search'
    | '/tickets'
    | '/upcoming'
    | '/exhibition/$exhibitionId'
    | '/reservation/$reservationId'
    | '/exhibition/$exhibitionId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/for-you'
    | '/profile'
    | '/search'
    | '/tickets'
    | '/upcoming'
    | '/exhibition/$exhibitionId'
    | '/reservation/$reservationId'
    | '/exhibition/$exhibitionId/book'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/for-you'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/tickets'
    | '/_authenticated/upcoming'
    | '/_authenticated/exhibition/$exhibitionId'
    | '/_authenticated/reservation/$reservationId'
    | '/_authenticated/exhibition/$exhibitionId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/for-you': {
      id: '/_authenticated/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof AuthenticatedForYouRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upcoming': {
      id: '/_authenticated/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof AuthenticatedUpcomingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exhibition/$exhibitionId': {
      id: '/_authenticated/exhibition/$exhibitionId'
      path: '/exhibition/$exhibitionId'
      fullPath: '/exhibition/$exhibitionId'
      preLoaderRoute: typeof AuthenticatedExhibitionExhibitionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservation/$reservationId': {
      id: '/_authenticated/reservation/$reservationId'
      path: '/reservation/$reservationId'
      fullPath: '/reservation/$reservationId'
      preLoaderRoute: typeof AuthenticatedReservationReservationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exhibition/$exhibitionId/book': {
      id: '/_authenticated/exhibition/$exhibitionId/book'
      path: '/book'
      fullPath: '/exhibition/$exhibitionId/book'
      preLoaderRoute: typeof AuthenticatedExhibitionExhibitionIdBookRouteImport
      parentRoute: typeof AuthenticatedExhibitionExhibitionIdRoute
    }
  }
}

interface AuthenticatedExhibitionExhibitionIdRouteChildren {
  AuthenticatedExhibitionExhibitionIdBookRoute: typeof AuthenticatedExhibitionExhibitionIdBookRoute
}

const AuthenticatedExhibitionExhibitionIdRouteChildren: AuthenticatedExhibitionExhibitionIdRouteChildren =
  {
    AuthenticatedExhibitionExhibitionIdBookRoute:
      AuthenticatedExhibitionExhibitionIdBookRoute,
  }

const AuthenticatedExhibitionExhibitionIdRouteWithChildren =
  AuthenticatedExhibitionExhibitionIdRoute._addFileChildren(
    AuthenticatedExhibitionExhibitionIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedForYouRoute: typeof AuthenticatedForYouRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedUpcomingRoute: typeof AuthenticatedUpcomingRoute
  AuthenticatedExhibitionExhibitionIdRoute: typeof AuthenticatedExhibitionExhibitionIdRouteWithChildren
  AuthenticatedReservationReservationIdRoute: typeof AuthenticatedReservationReservationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedForYouRoute: AuthenticatedForYouRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedUpcomingRoute: AuthenticatedUpcomingRoute,
  AuthenticatedExhibitionExhibitionIdRoute:
    AuthenticatedExhibitionExhibitionIdRouteWithChildren,
  AuthenticatedReservationReservationIdRoute:
    AuthenticatedReservationReservationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
